# Generated by Django 2.2 on 2019-06-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20190610_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
