# Generated by Django 2.2 on 2019-06-11 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_delete_produce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Crops')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.UserProfile')),
            ],
        ),
    ]
