# Generated by Django 2.2 on 2019-06-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_produce'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
