# Generated by Django 2.2 on 2019-06-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='emp_name',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
