# Generated by Django 2.2 on 2019-06-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_auto_20190611_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('used_for_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Crops')),
            ],
        ),
    ]
