# Generated by Django 2.2 on 2019-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_produce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='produce',
            name='date_submitted',
            field=models.DateField(),
        ),
    ]
