# Generated by Django 2.2 on 2019-06-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_financialrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produce',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
