# Generated by Django 2.2 on 2019-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_auto_20190619_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
