# Generated by Django 2.2 on 2019-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_auto_20190619_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecords',
            name='receipt_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
