# Generated by Django 2.2 on 2019-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_auto_20190623_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmMachinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinery_types', models.CharField(choices=[('TR', 'Tractors'), ('CO', 'Combines'), ('PL', 'Planters'), ('MO', 'Mowers'), ('SP', 'Sprayers'), ('PO', 'Plows')], max_length=2)),
                ('machinery_name', models.CharField(max_length=60)),
                ('identification_no', models.CharField(max_length=20)),
                ('machine_status', models.CharField(choices=[('AV', 'Available'), ('IM', 'In Maintenance')], max_length=2)),
                ('last_serviced', models.DateField()),
                ('date_of_purchase', models.DateField()),
            ],
        ),
    ]
