# Generated by Django 2.2 on 2019-06-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_farmmachinery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmmachinery',
            old_name='machinery_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='farmmachinery',
            old_name='machine_status',
            new_name='status',
        ),
    ]
