# Generated by Django 2.2 on 2019-06-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_auto_20190623_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmmachinery',
            old_name='machinery_types',
            new_name='machinery_type',
        ),
    ]
