# Generated by Django 2.2 on 2019-06-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_auto_20190623_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed',
            old_name='seed_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='seed',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialrecords',
            name='date_of_payment',
            field=models.DateField(),
        ),
    ]
