# Generated by Django 2.2 on 2019-06-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_auto_20190626_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_quantity', models.PositiveIntegerField()),
                ('crop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Crops')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Produce')),
            ],
        ),
    ]
