# Generated by Django 2.2 on 2019-06-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_producesold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producesold',
            name='crop_name',
        ),
    ]
