# Generated by Django 2.2 on 2019-06-27 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_remove_producesold_crop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producesold',
            name='date_sold',
            field=models.DateField(default=datetime.datetime(2019, 6, 27, 4, 6, 30, 259296, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
