# Generated by Django 2.2 on 2019-06-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_producesold_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='producesold',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
